"""Severity + preventability weights lookup (from category_weights.csv).

The CSV is the team's living lookup, regenerated by
``scripts/prepare_category_weights.py``. It always has seven columns:
``category, severity_weight_mean, severity_weight_median,
preventability_multiplier, preventability_tier, preventability_confidence,
preventability_anchor``. Anti-social behaviour carries blank (NaN) severity
because it is non-notifiable and outside CCHI's scope.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

import pandas as pd

from core.paths import WEIGHTS_CSV

WEIGHT_COLUMNS: tuple[str, ...] = (
    "category",
    "severity_weight_mean",
    "severity_weight_median",
    "preventability_multiplier",
    "preventability_tier",
    "preventability_confidence",
    "preventability_anchor",
)


@dataclass(frozen=True)
class CategoryMeta:
    """Per-category metadata surfaced by /api/meta and the sources panel."""

    name: str
    preventability_tier: str
    preventability_confidence: str
    preventability_anchor: str


@lru_cache(maxsize=1)
def load_weights() -> pd.DataFrame:
    """Load category_weights.csv. The ``major_category``→``category`` rename is
    kept for parity with the original app even though current CSVs already use
    ``category`` (rename is a no-op when the column is absent)."""
    return pd.read_csv(WEIGHTS_CSV).rename(columns={"major_category": "category"})


def category_metadata() -> list[CategoryMeta]:
    """Return per-category preventability metadata, ordered as in the CSV."""
    weights = load_weights()
    return [
        CategoryMeta(
            name=str(row["category"]),
            preventability_tier=str(row["preventability_tier"]),
            preventability_confidence=str(row["preventability_confidence"]),
            preventability_anchor=str(row["preventability_anchor"]),
        )
        for _, row in weights.iterrows()
    ]


def weights_records() -> list[dict]:
    """Full weights table as JSON-safe records (NaN -> None) for /api/weights."""
    weights = load_weights()
    return weights.where(pd.notna(weights), None).to_dict(orient="records")
